version: "3.6"

services:
  db:
    image: postgres:9.5.4
    # https://docs.docker.com/compose/compose-file/#ports
    expose:
      - "5432"
    # https://docs.docker.com/compose/compose-file/#volumes
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.development
    environment:
      DB_URL: "ecto://postgres@db:5432/changelog_dev"
      VIRTUAL_HOST: &host "${HOST:-localhost}"
      HOST: *host
    ports:
      - "4000:4000"
    volumes:
      - build:/app/_build
      - ./assets:/app/assets
      - node_modules:/app/assets/node_modules
      - ./config:/app/config
      - deps:/app/deps
      - ./lib:/app/lib
      - ./priv:/app/priv
      - ./script:/app/script
      - ./test:/app/test
      - ./.all-contributorsrc:/app/.all-contributorsrc
      - ./.credo.exs:/app/.credo.exs
      - ./.iex.exs:/app/.iex.exs
      - ./mix.exs:/app/mix.exs
      - ./mix.lock:/app/mix.lock
    depends_on:
      - db
  proxy:
    image: thechangelog/proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d/changelog.conf:/etc/nginx/conf.d/changelog.conf:ro
      - ./priv/uploads/:/var/www/uploads:ro

volumes:
  postgres:
  build:
  deps:
  node_modules:
